### ISSUE TITLE
Question thread

### ISSUE THREAD

**Issue by jitendra3109** [cassidoo/talks#1]
Is that okay to reach out?
First of All, I would like to intro myself:
Hi! My name is Jitendra Singh, Senior year CSE B. tech from IIIT VADODARA[INDIA].
Since last year I start Open Source Contribution and I love it.
Lost thing to tell but will take offline.

So Here is my couple question.
1. Would you like to share your resume?
2.What could be the answer of why we hire you to form tech guys to HR?

**Comment by cassidoo** [comment]
1) You can check out my website at cassidoo.co!
2) I'm not sure what this question means, but thanks for reaching out!
