### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Andrea** [cassidoo/talks#4]
Hi there

I wanted to use your rider as inspiration, however I see there is no License? 
Maybe even just for the rider(I didn't know that was the name for it) 
Cheers

**Comment by cassidoo** [comment]
Go ahead and take it, if you'd like to link back to it, you can say "I'm using Cassidy's rider as a basis: cass.run/rider" :)

**Comment by Andrea** [comment]
Thanks :smile:
